services:
  xmrig:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    image: xmrig
    container_name: xmrig
    privileged: true
    restart: unless-stopped
    volumes:
      - ./config.json:/root/.xmrig.json
