name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
permissions: 
  contents: read
  packages: write
  actions: write

jobs:
  build:
    permissions:
      contents: read
      packages: write
      actions: write
    runs-on: ubuntu-latest
    steps:
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          logout: false
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/korewachino/xmrig:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max